### ISSUE TITLE
AP calculate problem ?

### ISSUE THREAD

**Issue by Anida-qin** [asharakeh/kitti_native_evaluation#1]
hi~
@asharakeh 
I m not quite understand the AP here now. I think it should sum[0]/41*100 because here it separate recall into 41 slices. 
`
void printAp(string file_name, vector<double> vals[]){

  float sum[3] = {0, 0, 0};
  for (int v = 0; v < 3; ++v)
    for (int i = 0; i < vals[v].size(); i = i + 4)
      sum[v] += vals[v][i];
  printf("%s AP: %f %f %f\n", file_name.c_str(), sum[0] / 11 * 100, sum[1] / 11 * 100, sum[2] / 11 * 100);

}
`
Also i m a little confused about less than 41 thresholds, because if there is only 20 thresholds. The recall and the precision are not match. And the AP here should be sum[0]/20. 
Extreme case, only one threshold, precision 1 but the result will look like this:
0        1  1  1
0.025  0  0  0
0.050  0  0  0
0.075  0  0  0
0.100  0  0  0
0.125  0  0  0
0.150  0  0  0
0.175  0  0  0

Maybe i had some misunderstanding here. Can u help me ?
Thanks a lot !!!

**Comment by asharakeh** [comment]
@Anida-qin you are correct, integration of the P-R curve over 41 bins in recall is a more precise than 11. However, KITTI complies with the metric of PASCAL VOC 2011 challenge as described in the paper: 

http://host.robots.ox.ac.uk/pascal/VOC/pubs/everingham10.pdf

**Comment by Anida-qin** [comment]
I understand now. Thanks a lot !
