### ISSUE TITLE
The meaning of the output

### ISSUE THREAD

**Issue by jiaminglei-lei** [asharakeh/kitti_native_evaluation#10]
Hello @asharakeh 
I used your script to evaluate the result. But I am confused the meaning of those outputs. For example, 

1.  when the script was running, it outputted: `car_detection_AP : 90.716682 89.915375 89.342400`. Are these three numbers mean the AP of model on three difficulty level: easy, moderate and hard?
2.  The script created a new folder named 'plot'. In this folder, there are two types of files, '.txt' and '.gp', could you pls explain the content in these files? '.gp' files are used to plot the AP curve? If 'yes', how to do?
3. Also, the script outputted three '.txt' files: 'stats_car_detection.txt', 'stats_car_detection_ground.txt', 'stats_car_orientation.txt', what's the meaning of the numbers in these three files?

Thank you for your help!!

**Comment by asharakeh** [comment]
1. Yes, you are correct.
2. I believe you should install a library that is required for these plots to work. I have not used this code in a long time but if I remember correctly it has something to do with PDF ghostscript https://www.ghostscript.com/.
3. Those are the points used to generate the AP plot, again this is from memory as I have not used this code in a long time.

**Comment by phoebedddd** [comment]
> Hello @asharakeh I used your script to evaluate the result. But I am confused the meaning of those outputs. For example,
> 
> 1. when the script was running, it outputted: `car_detection_AP : 90.716682 89.915375 89.342400`. Are these three numbers mean the AP of model on three difficulty level: easy, moderate and hard?
> 2. The script created a new folder named 'plot'. In this folder, there are two types of files, '.txt' and '.gp', could you pls explain the content in these files? '.gp' files are used to plot the AP curve? If 'yes', how to do?
> 3. Also, the script outputted three '.txt' files: 'stats_car_detection.txt', 'stats_car_detection_ground.txt', 'stats_car_orientation.txt', what's the meaning of the numbers in these three files?
> 
> Thank you for your help!!
How do you generate estimates of pedestrians and bicycles?
