### ISSUE TITLE
AN ERROR ：couldn't   read

### ISSUE THREAD

**Issue by molong-d** [asharakeh/kitti_native_evaluation#14]
ERROR: Couldn't read: 002863.txt of ground truth. Please write me an email!
An error occured while processing your results.

Dear author, hello. I have encountered this problem now, and I really do not know how to solve it. How can I solve this problem

**Comment by NiranjanRavi1993** [comment]
Hi @molong-d , how did you resolve this issue?  I am facing the same.

**Comment by molong-d** [comment]
Sorry, I didn't solve it.

**Comment by NiranjanRavi1993** [comment]
Any other work around possible?
