### ISSUE TITLE
stopped with segmentation fault

### ISSUE THREAD

**Issue by jkstyle2** [asharakeh/kitti_native_evaluation#4]
First, thanks for your amazing work!
While it's really helpful, I really need your help.
Here are the summary I'm currently seeing.

> car_detection_AP : 85.031853 81.267220 74.636650
> sh: 1: gnuplot: not found
> sh: 1: gnuplot: not found
> Error: /undefinedfilename in (car_detection_AP.eps)
> Operand stack:
> 
> Execution stack:
>    %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
> Dictionary stack:
>    --dict:961/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--
> Current allocation mode is local
> Last OS error: No such file or directory
> GPL Ghostscript 9.26: Unrecoverable error, exit code 1
> sh: 1: pdfcrop: not found
> car_orientation_AOS : 84.987823 79.064232 69.322250
> sh: 1: gnuplot: not found
> sh: 1: gnuplot: not found
> Error: /undefinedfilename in (car_orientation_AOS.eps)
> Operand stack:
> 
> Execution stack:
> ...
> ...
> ...
> Execution stack:
>    %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
> Dictionary stack:
>    --dict:961/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--
> Current allocation mode is local
> Last OS error: No such file or directory
> GPL Ghostscript 9.26: Unrecoverable error, exit code 1
> sh: 1: pdfcrop: not found

When it starts evaluating bird's eye detection, a critical segmentation fault occurs, and it's all stopped.
It has been happening in other similar projects, but I can't figure out what the real issues are.
It will be so helpful if you could give me some piece of hints. Thanks in advance.

Apart from this issue, I have one more question.
How can we decide the 16th value 'score/confidence' in the label? This time, I just put any random number, but I have no idea of calculating the value. Does it come from 2D Detector which usually outputs confidence probability by softmax classification?

Again, thanks for you work, and looking forward to seeing your reply!

**Comment by asharakeh** [comment]
@jkstyle2 the seg fault can occur for multiple reasons. For example, in case the bounding box coordinates are not what the software expects (-ve z coordinate in 3D, x_min > x_max in 2D, etc...). It can also happen if you have negative score values.  

In summary, if it is happening for every kitti eval, then it is a problem with your data not with the evaluation code.

The score label should be the class probability output from your object detector, specifically the softmax output of the highest class in case you use softmax.

**Comment by jmiemirza** [comment]
Yes. Same thing has been happening with me as well. I am using my own data and not the original KITTI data.  It just gives me the Car Detection AP and then throws a segmentation fault. 

However, did anyone figure out a way to get around it or deal with it?
