### ISSUE TITLE
there is a problem when i'm running

### ISSUE THREAD

**Issue by yxy1995123** [asharakeh/kitti_native_evaluation#5]

**Comment by yxy1995123** [comment]
> when i ran ./evaluate_object_3d_offline gt_dir result_dir，it produced a file named 'plot',but there was nothing in 'plot' file,so where is the evaluation result?

**Comment by sarimmehdi** [comment]
Hi. I have the same issue. How did you solve this?

**Comment by Bynow76** [comment]
I have the same issue. How did you solve this?

**Comment by sarimmehdi** [comment]
This issue is still not solved. Please tell us how you solved it @yxy1995123 

Edit: This issue can be solved by keeping your detection text files in a folder called data and then passing the path of the folder that contains the 'data' folder

**Comment by CrabbyRabbit** [comment]
I have the same issue,too. did anyone solve this？
