### ISSUE TITLE
Can someone explain AP and AOS to me?

### ISSUE THREAD

**Issue by sarimmehdi** [asharakeh/kitti_native_evaluation#8]
Hello. I wanted to understand the following terms:
- **overlap on image (AP)**
- **oriented overlap on image (AOS)**
- **overlap on ground-plane (AP)**
- **oriented overlap on ground-plane (AHS)**
- **overlap in 3D (AP)**
- **oriented overlap in 3D (3D AHS)**

As far as I understand (do correct me if I am wrong), kitti measures the 3D intersection over union between the 3D bounding boxes. In light of that, can you explain to me what all the above terms mean? Thank you!

**Comment by asharakeh** [comment]
@sarimmehdi kitti measures: 
1. 2D IOU in image space.
2. Oriented 2D IOU in BEV space.
3. Oriented 3D IOU in 3D space.

After that:
- overlap on image (AP) uses 2D IOU in image space..
- oriented overlap on image (AOS) uses 2D IOU in image space.
- overlap on ground-plane (AP) uses 2D IOU in BEV space.
- oriented overlap on ground-plane (AHS) uses 2D IOU in BEV space.
- overlap in 3D (AP) uses 3D IOU.
- oriented overlap in 3D (3D AHS) uses 3D IOU.
