### ISSUE TITLE
Your script doesn't work

### ISSUE THREAD

**Issue by sarimmehdi** [asharakeh/kitti_native_evaluation#9]
I tried to use your script but it just creates an empty folder named plot. My detection file looks like this (I am trying to evaluate 3D object detection):

`Pedestrian -1 -1 -10 699 152 839 307 1.79355319183269 2.864534433991117 1.255055899107495 2.0412647769700696 1.4699194190575617 9.589653289755141 0.01 0.9991099`

**Comment by sarimmehdi** [comment]
Edit: This issue can be solved by keeping your detection text files in a folder called data and then passing the path of the folder that contains the 'data' folder

**Comment by PuJanhan** [comment]
Hi，I use   ./evaluate_object_offline DATASET_ROOT_DIR/labels/training/label_2/ /home/fuhao/Point-GNN/DIR_TO_SAVE_RESULTS/data  and it also create  an empty folder named plot
My detection file looks like this(evaluate 3D object detection)
Car -1 -1 0 448.2340269277761 181.78251854827707 514.1682426258046 221.1665358343806 1.549426 1.6574428 3.7241025 -5.482465 1.9606047 31.254852 1.7372551 1.3187539886617212 
Car -1 -1 0 462.47009208721033 182.31281392159576 509.2109330656136 214.0116311967497 1.5387392 1.651661 3.6661131 -6.4613686 2.0617464 38.02036 1.6258419 0.27413129806518555 

Could you give some advice?

**Comment by jiachen-zhou** [comment]
> Hi，I use ./evaluate_object_offline DATASET_ROOT_DIR/labels/training/label_2/ /home/fuhao/Point-GNN/DIR_TO_SAVE_RESULTS/data and it also create an empty folder named plot
> My detection file looks like this(evaluate 3D object detection)
> Car -1 -1 0 448.2340269277761 181.78251854827707 514.1682426258046 221.1665358343806 1.549426 1.6574428 3.7241025 -5.482465 1.9606047 31.254852 1.7372551 1.3187539886617212
> Car -1 -1 0 462.47009208721033 182.31281392159576 509.2109330656136 214.0116311967497 1.5387392 1.651661 3.6661131 -6.4613686 2.0617464 38.02036 1.6258419 0.27413129806518555
> 
> Could you give some advice?

As suggested by @sarimmehdi, passing the path of the folder that **contains** the 'data' folder should work. So in your case, I believe it'd be `./evaluate_object_offline DATASET_ROOT_DIR/labels/training/label_2/ /home/fuhao/Point-GNN/DIR_TO_SAVE_RESULTS/`
